services:
  # Python FastAPI Service
  - type: web
    name: mediskin-python-api
    runtime: image
    repo: https://github.com/nelnel19/MediSkin-Backend
    branch: main
    dockerfilePath: ./Dockerfile.python
    plan: free
    region: singapore
    envVars:
      - key: MONGO_URI
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
    healthCheckPath: /

  # Node.js Service
  - type: web
    name: mediskin-node-api
    runtime: image
    repo: https://github.com/nelnel19/MediSkin-Backend
    branch: main
    dockerfilePath: ./Dockerfile.node
    plan: free
    region: singapore
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
    healthCheckPath: /health